### PR TITLE
Add support for Symfony 5 and 6

### PR DESCRIPTION
**Pull request by loic425**

### CODE REVIEW

**Comment by loic425** [comment]
@pamil @lchrusciel Could you re-activate github actions please?

**Comment by Zales0123** [comment]
I'm neither of them, but I've made GH work 😄 🖖

**Comment by loic425** [comment]
@pamil I removed testing phpspec for now on Symfony 6 
It's not compatible yet, but a pull-request is open => https://github.com/phpspec/phpspec/pull/1402

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
Thanks @loic425! 🎉

**Pull request merged**
